"""
agent/state.py — Shared LangGraph state and typed result structures.

AgentState is the single source of truth passed between all graph nodes.
JudgeAttaccoResult and JudgePatchResult are the structured outputs of the
two judge nodes; they are stored inside AgentState.
"""

from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph.message import add_messages


class JudgeAttaccoResult(TypedDict):
    """Structured output from node_judge_attacco."""

    successo: bool
    """Whether the attack actually succeeded (forced from node_esegui_attacco, not decided by LLM)."""

    motivazione: str
    """Clear explanation of why the attack succeeded or failed."""

    tecnica_usata: str
    """Name and description of the SQLi technique used in the payload."""

    suggerimento: str
    """If failed: what the red team should try differently.
    If succeeded: what made the attack effective."""


class JudgePatchResult(TypedDict):
    """Structured output from node_judge_patch."""

    funzionale: bool
    """True if the patch blocks the attack (forced from node_valida_patch result, not decided by LLM)."""

    qualita_codice: str
    """One of: 'ottima' | 'sufficiente' | 'insufficiente'."""

    problemi: str
    """List of problems found in the patch, or 'nessuno'."""

    motivazione: str
    """Explanation: does the patch block the attack? Is the code well written?"""


class AgentState(TypedDict):
    """Complete shared state for the DVWA LangGraph multi-agent pipeline.

    Lifecycle:
    - Initialised in main.py before graph.invoke()
    - Each node returns a dict with a subset of these keys; LangGraph merges them
    - `messages` uses add_messages reducer (append-only)
    - All other fields are last-write-wins
    """

    # ── Red Team ────────────────────────────────────────────────────────────
    messages: Annotated[list, add_messages]
    """Conversation history for the red team LLM (append-only via add_messages)."""

    tentativo: int
    """Current attack attempt counter (1-indexed after first increment)."""

    payload: str
    """Last SQL Injection payload generated by the red team."""

    # ── HTTP execution ───────────────────────────────────────────────────────
    risposta_http_raw: str
    """Cleaned text response from the DVWA HTTP endpoint (≤2000 chars)."""

    attacco_successo: bool
    """Deterministic fact: True iff ≥2 'First name:' occurrences found in response."""

    sessione_scaduta: bool
    """True if DVWA redirected to login.php — session cookie is expired."""

    # ── Judge Attacco ────────────────────────────────────────────────────────
    judge_attacco: JudgeAttaccoResult
    """LLM reasoning output from node_judge_attacco."""

    # ── Blue Team ────────────────────────────────────────────────────────────
    codice_originale: str
    """Original vulnerable PHP source, read once by node_init and never overwritten."""

    patch_applicata: bool
    """True if node_blue_team successfully wrote a patch to disk."""

    tentativo_patch: int
    """Current patch attempt counter (starts at 0, incremented in node_blue_team)."""

    # ── Validation ────────────────────────────────────────────────────────────
    regression_test_passed: bool
    """True if the functional regression tests passed after patching."""

    # ── Judge Patch ──────────────────────────────────────────────────────────
    judge_patch: JudgePatchResult
    """LLM reasoning output from node_judge_patch."""

    # ── Metriche di Valutazione ──────────────────────────────────────────────
    num_diff_applicati_successo: int
    """Numero di patch (diff) applicate con successo (senza conflitti)."""

    num_test_funzionali_passati: int
    """Numero di tentativi in cui i test di regressione funzionale sono passati."""

    num_errori_sintassi: int
    """Numero totale di errori di sintassi PHP riscontrati (PHP linting)."""

    dettagli_sintassi: list[str]
    """Lista dei dettagli degli errori di sintassi rilevati durante le run."""

    dettagli_applicazione: list[str]
    """Lista delle descrizioni degli errori riscontrati durante l'applicazione delle patch."""

